# Generated by Django 5.1.6 on 2025-02-18 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('managerid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('ownerid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('apartmentid', models.AutoField(primary_key=True, serialize=False)),
                ('apartment_num', models.CharField(max_length=10)),
                ('floor', models.IntegerField()),
                ('building_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied')], max_length=20)),
                ('managerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Amsapp.manager')),
                ('ownerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Amsapp.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenantid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=15)),
                ('movedate', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Amsapp.apartment')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('requestid', models.AutoField(primary_key=True, serialize=False)),
                ('requestdate', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='maintenance_images/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], max_length=20)),
                ('apartmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Amsapp.apartment')),
                ('tenantid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Amsapp.tenant')),
            ],
        ),
    ]
